const URL = {
  HOME: '/home',
  DESIGN: '/design',
  DESIGN_SPEC: '/design/spec',
  DESIGN_COLOR: '/design/color',
  DESIGN_CUSTOMIZED: '/design/customized',
  COMPONENTS: '/components',
  COMPONENTS_BREADCRUMB: '/components/breadcrumb',
  COMPONENTS_BUTTON: '/components/button',
  COMPONENTS_BUTTONGROUP: '/components/button-group',
  COMPONENTS_DROPDOWN: '/components/dropdown',
  COMPONENTS_DROPDOWNBUTTON: '/components/dropdown-button',
  COMPONENTS_INPUTNUMBER: '/components/input-number',
  COMPONENTS_INPUTSEARCH: '/components/input-search',
  COMPONENTS_MENU: '/components/menu',
  COMPONENTS_NOTIFICATION: '/components/notification',
  COMPONENTS_PAGINATION: '/components/pagination',
  COMPONENTS_PANEL: '/components/panel',
  COMPONENTS_SLIDER: '/components/slider',
  COMPONENTS_STEP: '/components/step',
  COMPONENTS_SWITCH: '/components/switch',
  COMPONENTS_TAB: '/components/tab',
  COMPONENTS_TABLE: '/components/table',
  COMPONENTS_TIP: '/components/tip',
  COMPONENTS_TOOLTIP: '/components/tooltip',
  ABOUT: '/about',
  ABOUT_MEMBERS: '/about/members'
};

export { URL };
